/* The following code was generated by JFlex 1.6.1 */


/* --------------------------Codigo de Usuario----------------------- */
package parser.data;

import java_cup.runtime.*;
import java.io.Reader;
import static parser.data.Token.*;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/parser/data/reglas_lexicas.flex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING_STATE = 2;
  public static final int COMENTARIO_STATE = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\5\1\13\1\7\1\4\22\0\1\6\1\52\1\10"+
    "\1\23\1\0\1\51\1\45\1\11\1\46\1\47\1\53\1\50\1\60"+
    "\1\22\1\0\1\54\1\2\10\3\1\3\1\62\1\61\1\12\1\55"+
    "\1\14\2\0\4\1\1\1\1\1\5\1\1\20\10\1\1\16\5\1"+
    "\4\0\1\1\1\0\1\31\1\40\1\33\1\24\1\21\1\25\1\32"+
    "\1\41\1\26\1\1\1\42\1\17\1\1\1\27\1\35\1\1\1\1"+
    "\1\34\1\30\1\36\1\15\1\37\1\43\1\1\1\1\1\1\1\56"+
    "\1\44\1\57\7\0\1\13\u1fa2\0\1\13\1\13\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\2\3\2\4\1\5\1\1\1\6"+
    "\1\7\2\2\1\10\1\11\11\2\2\1\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\2\30\1\31\2\1\3\3"+
    "\3\0\1\32\1\33\1\34\2\2\1\35\1\36\1\2"+
    "\1\37\1\2\1\40\13\2\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\4\1\51\1\52\2\3"+
    "\1\53\2\0\1\32\3\2\1\54\1\2\1\55\13\2"+
    "\2\0\2\32\1\56\1\57\4\2\1\60\2\2\1\61"+
    "\1\62\1\2\1\63\3\2\1\0\1\4\2\2\1\64"+
    "\1\2\1\65\2\2\1\66\1\67\1\70\2\2\1\71"+
    "\1\2\1\72\1\73\1\74\1\2\1\75";

  private static int [] zzUnpackAction() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\377\0\u0132\0\u0165"+
    "\0\231\0\231\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297"+
    "\0\231\0\u02ca\0\u02fd\0\u0330\0\u0363\0\u0396\0\u03c9\0\u03fc"+
    "\0\u042f\0\u0462\0\u0495\0\u04c8\0\231\0\231\0\u04fb\0\u052e"+
    "\0\u0561\0\u0594\0\u05c7\0\u05fa\0\231\0\231\0\231\0\231"+
    "\0\231\0\u062d\0\u0660\0\231\0\231\0\377\0\u0693\0\u06c6"+
    "\0\u06f9\0\u0693\0\u072c\0\u075f\0\u0792\0\u075f\0\u075f\0\231"+
    "\0\u07c5\0\u07f8\0\231\0\231\0\u082b\0\314\0\u085e\0\314"+
    "\0\u0891\0\u08c4\0\u08f7\0\u092a\0\u095d\0\u0990\0\u09c3\0\u09f6"+
    "\0\u0a29\0\u0a5c\0\u0a8f\0\231\0\231\0\231\0\231\0\231"+
    "\0\231\0\231\0\u0ac2\0\u0af5\0\231\0\231\0\u0b28\0\231"+
    "\0\231\0\u0b5b\0\u0b8e\0\u0b8e\0\u0bc1\0\u0bf4\0\u0c27\0\314"+
    "\0\u0c5a\0\314\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26\0\u0d59\0\u0d8c"+
    "\0\u0dbf\0\u0df2\0\u0e25\0\u0e58\0\u0e8b\0\u0ebe\0\u0ef1\0\231"+
    "\0\u0b5b\0\314\0\314\0\u0f24\0\u0f57\0\u0f8a\0\u0fbd\0\314"+
    "\0\u0ff0\0\u1023\0\314\0\314\0\u1056\0\314\0\u1089\0\u10bc"+
    "\0\u10ef\0\u1122\0\u0ebe\0\u1155\0\u1188\0\314\0\u11bb\0\314"+
    "\0\u11ee\0\u1221\0\314\0\314\0\314\0\u1254\0\u1287\0\314"+
    "\0\u12ba\0\314\0\314\0\314\0\u12ed\0\314";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\3\11\1\12\1\13"+
    "\1\14\1\0\1\15\2\5\1\16\1\5\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\5\1\25\2\5\1\26"+
    "\1\27\2\5\1\30\1\31\2\5\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\4\52\1\53\1\54"+
    "\2\52\1\55\52\52\53\11\1\0\7\11\64\0\1\5"+
    "\1\0\1\5\11\0\5\5\2\0\20\5\21\0\2\56"+
    "\60\0\1\57\1\60\1\7\11\0\2\61\2\62\1\57"+
    "\2\0\20\57\24\0\1\11\55\0\4\63\2\0\55\63"+
    "\1\64\1\65\2\64\2\0\1\64\1\0\3\64\1\0"+
    "\1\66\5\65\2\64\20\65\11\64\1\67\5\64\55\0"+
    "\1\70\6\0\1\5\1\0\1\5\11\0\5\5\2\0"+
    "\11\5\1\71\6\5\20\0\1\5\1\0\1\5\11\0"+
    "\2\5\1\72\2\5\2\0\20\5\41\0\1\73\32\0"+
    "\1\74\6\0\1\5\1\0\1\5\11\0\4\5\1\75"+
    "\2\0\11\5\1\76\6\5\20\0\1\5\1\0\1\5"+
    "\11\0\5\5\2\0\11\5\1\77\6\5\20\0\1\5"+
    "\1\0\1\5\11\0\5\5\2\0\1\5\1\100\1\5"+
    "\1\101\14\5\20\0\1\5\1\0\1\5\11\0\5\5"+
    "\2\0\15\5\1\102\1\5\1\103\20\0\1\5\1\0"+
    "\1\5\11\0\5\5\2\0\5\5\1\104\3\5\1\105"+
    "\3\5\1\106\2\5\20\0\1\5\1\0\1\5\11\0"+
    "\4\5\1\107\2\0\20\5\20\0\1\5\1\0\1\5"+
    "\11\0\5\5\2\0\11\5\1\110\6\5\20\0\1\5"+
    "\1\0\1\5\11\0\5\5\2\0\10\5\1\111\7\5"+
    "\20\0\1\5\1\0\1\5\11\0\5\5\2\0\10\5"+
    "\1\112\4\5\1\113\2\5\63\0\1\114\63\0\1\115"+
    "\65\0\1\116\4\0\1\117\62\0\1\120\62\0\1\121"+
    "\62\0\1\122\60\0\1\123\1\124\1\125\62\0\1\126"+
    "\5\0\4\52\2\0\2\52\1\0\52\52\5\0\1\54"+
    "\56\0\1\57\1\0\1\57\11\0\5\57\2\0\20\57"+
    "\21\0\2\60\11\0\2\127\2\130\43\0\1\57\1\0"+
    "\1\57\11\0\2\57\2\62\1\57\2\0\20\57\30\0"+
    "\1\131\51\0\4\132\2\0\2\132\1\0\52\132\1\133"+
    "\1\65\2\133\2\0\1\133\1\132\1\64\2\133\1\132"+
    "\1\134\5\65\2\133\20\65\17\133\1\0\1\5\1\0"+
    "\1\5\11\0\5\5\2\0\3\5\1\135\14\5\20\0"+
    "\1\5\1\0\1\5\11\0\5\5\2\0\4\5\1\136"+
    "\13\5\20\0\1\5\1\0\1\5\11\0\5\5\2\0"+
    "\1\5\1\137\16\5\20\0\1\5\1\0\1\5\11\0"+
    "\5\5\2\0\10\5\1\140\7\5\20\0\1\5\1\0"+
    "\1\5\11\0\5\5\2\0\7\5\1\141\2\5\1\142"+
    "\5\5\20\0\1\5\1\0\1\5\11\0\5\5\2\0"+
    "\11\5\1\143\6\5\20\0\1\5\1\0\1\5\11\0"+
    "\5\5\2\0\2\5\1\144\15\5\20\0\1\5\1\0"+
    "\1\5\11\0\5\5\2\0\4\5\1\145\13\5\20\0"+
    "\1\5\1\0\1\5\11\0\5\5\2\0\3\5\1\146"+
    "\14\5\20\0\1\5\1\0\1\5\11\0\5\5\2\0"+
    "\5\5\1\147\12\5\20\0\1\5\1\0\1\5\11\0"+
    "\5\5\2\0\5\5\1\150\4\5\1\151\5\5\20\0"+
    "\1\5\1\0\1\5\11\0\5\5\2\0\2\5\1\152"+
    "\15\5\20\0\1\5\1\0\1\5\11\0\4\5\1\153"+
    "\2\0\20\5\20\0\1\5\1\0\1\5\11\0\5\5"+
    "\2\0\2\5\1\154\15\5\20\0\1\5\1\0\1\5"+
    "\11\0\5\5\2\0\2\5\1\155\15\5\17\0\53\156"+
    "\1\157\7\156\4\124\1\10\1\11\2\124\1\0\52\124"+
    "\17\0\2\130\56\0\1\160\46\0\4\132\2\0\2\132"+
    "\1\0\3\132\1\161\46\132\1\0\1\5\1\0\1\5"+
    "\11\0\5\5\2\0\6\5\1\162\11\5\20\0\1\5"+
    "\1\0\1\5\11\0\4\5\1\163\2\0\20\5\20\0"+
    "\1\5\1\0\1\5\11\0\5\5\2\0\5\5\1\164"+
    "\12\5\20\0\1\5\1\0\1\5\11\0\2\5\1\165"+
    "\2\5\2\0\20\5\20\0\1\5\1\0\1\5\11\0"+
    "\5\5\2\0\10\5\1\166\7\5\20\0\1\5\1\0"+
    "\1\5\11\0\5\5\2\0\12\5\1\167\5\5\20\0"+
    "\1\5\1\0\1\5\11\0\4\5\1\170\2\0\20\5"+
    "\20\0\1\5\1\0\1\5\11\0\5\5\2\0\4\5"+
    "\1\171\5\5\1\172\5\5\20\0\1\5\1\0\1\5"+
    "\11\0\5\5\2\0\10\5\1\173\7\5\20\0\1\5"+
    "\1\0\1\5\11\0\5\5\2\0\1\174\17\5\20\0"+
    "\1\5\1\0\1\5\11\0\1\175\4\5\2\0\20\5"+
    "\20\0\1\5\1\0\1\5\11\0\5\5\2\0\1\176"+
    "\17\5\20\0\1\5\1\0\1\5\11\0\5\5\2\0"+
    "\5\5\1\177\12\5\20\0\1\5\1\0\1\5\11\0"+
    "\5\5\2\0\12\5\1\200\5\5\20\0\1\5\1\0"+
    "\1\5\11\0\2\5\1\201\2\5\2\0\20\5\17\0"+
    "\53\156\1\202\62\156\1\202\1\203\6\156\1\0\1\5"+
    "\1\0\1\5\11\0\1\204\4\5\2\0\20\5\20\0"+
    "\1\5\1\0\1\5\11\0\1\205\4\5\2\0\20\5"+
    "\20\0\1\5\1\0\1\5\11\0\5\5\2\0\12\5"+
    "\1\206\5\5\20\0\1\5\1\0\1\5\11\0\5\5"+
    "\2\0\7\5\1\207\10\5\20\0\1\5\1\0\1\5"+
    "\11\0\5\5\2\0\12\5\1\210\5\5\20\0\1\5"+
    "\1\0\1\5\11\0\5\5\2\0\2\5\1\211\15\5"+
    "\20\0\1\5\1\0\1\5\11\0\5\5\2\0\10\5"+
    "\1\212\7\5\20\0\1\5\1\0\1\5\11\0\5\5"+
    "\2\0\16\5\1\213\1\5\20\0\1\5\1\0\1\5"+
    "\11\0\4\5\1\214\2\0\20\5\20\0\1\5\1\0"+
    "\1\5\11\0\4\5\1\215\2\0\20\5\17\0\53\156"+
    "\1\202\1\11\6\156\1\0\1\5\1\0\1\5\11\0"+
    "\2\5\1\216\2\5\2\0\20\5\20\0\1\5\1\0"+
    "\1\5\11\0\5\5\2\0\1\217\17\5\20\0\1\5"+
    "\1\0\1\5\11\0\5\5\2\0\15\5\1\220\2\5"+
    "\20\0\1\5\1\0\1\5\11\0\5\5\2\0\3\5"+
    "\1\221\14\5\20\0\1\5\1\0\1\5\11\0\5\5"+
    "\2\0\3\5\1\222\14\5\20\0\1\5\1\0\1\5"+
    "\11\0\5\5\2\0\12\5\1\223\5\5\20\0\1\5"+
    "\1\0\1\5\11\0\4\5\1\224\2\0\20\5\20\0"+
    "\1\5\1\0\1\5\11\0\1\225\4\5\2\0\20\5"+
    "\20\0\1\5\1\0\1\5\11\0\4\5\1\226\2\0"+
    "\20\5\17\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4896];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\4\1\2\11\6\1\1\11\13\1\2\11"+
    "\6\1\5\11\2\1\2\11\5\1\3\0\2\1\1\11"+
    "\2\1\2\11\17\1\7\11\2\1\2\11\1\1\2\11"+
    "\2\0\22\1\2\0\1\11\21\1\1\0\24\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Lexema lexema(Token type) {
        return new Lexema(type, yyline, yycolumn);
    }
    private Lexema lexema(Token type, Object value) {
        return new Lexema(type, value, yyline, yycolumn);
    }
    public String token;
    public String string;
    public Lexema lexeme;
    /*  Generamos un java_cup.Symbol para guardar el tipo de token 
        encontrado */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Generamos un Symbol para el tipo de token encontrado 
       junto con su valor */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 188) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case YYINITIAL: {
              return symbol(sym.EOF);
            }
            case 151: break;
            case STRING_STATE: {
              yybegin(YYINITIAL); string.concat(yytext()); 
                            lexeme = lexema(ERROR,string); return symbol(sym.error);
            }
            case 152: break;
            case COMENTARIO_STATE: {
              yybegin(YYINITIAL); lexeme = lexema(ERROR,yytext()); return symbol(sym.error);
            }
            case 153: break;
            default:
          { return new java_cup.runtime.Symbol(sym.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme = lexema(ERROR); return symbol(sym.error);
            }
          case 62: break;
          case 2: 
            { System.out.println(" IDENTIFICADOR "); 
                            lexeme = lexema(IDENTIFICADOR,yytext()); 
                            return symbol(sym.IDENTIFICADOR,yytext());
            }
          case 63: break;
          case 3: 
            { System.out.println(" NUMERO_ENTERO "); 
                            lexeme= lexema(LITERAL_ENTERO,yytext()); 
                            return symbol(sym.LITERAL_ENTERO, new Integer(yytext()));
            }
          case 64: break;
          case 4: 
            { /*Ignorar*/
            }
          case 65: break;
          case 5: 
            { string = "\""; yybegin(STRING_STATE);
            }
          case 66: break;
          case 6: 
            { System.out.println(" MENORQUE ");
                            return symbol(sym.MENORQUE,"<");
            }
          case 67: break;
          case 7: 
            { System.out.println(" MAYORQUE ");
                            return symbol(sym.MAYORQUE,">");
            }
          case 68: break;
          case 8: 
            { System.out.println(" SUBSTRACT ");
                            return symbol(sym.SUBSTRACT,"-");
            }
          case 69: break;
          case 9: 
            { System.out.println(" # ");
                            return symbol(sym.SIMBOLO_NUMERO,"#");
            }
          case 70: break;
          case 10: 
            { System.out.println(" LPAREN ");
                            return symbol(sym.LPAREN,"(");
            }
          case 71: break;
          case 11: 
            { System.out.println(" RPAREN ");
                            return symbol(sym.RPAREN,")");
            }
          case 72: break;
          case 12: 
            { System.out.println(" ADD ");
                            return symbol(sym.ADD,"+");
            }
          case 73: break;
          case 13: 
            { System.out.println(" MODULUS ");
                            return symbol(sym.MODULUS,"%");
            }
          case 74: break;
          case 14: 
            { System.out.println(" EXCLAMACION ");
                            return symbol(sym.EXCLAMACION,"!");
            }
          case 75: break;
          case 15: 
            { System.out.println(" TIMES ");
                            return symbol(sym.TIMES,"*");
            }
          case 76: break;
          case 16: 
            { System.out.println(" DIVISION ");
                            return symbol(sym.DIVISION,"/");
            }
          case 77: break;
          case 17: 
            { System.out.println(" ASSIGN ");
                            return symbol(sym.ASSIGN,"=");
            }
          case 78: break;
          case 18: 
            { System.out.println(" LBRACE ");
                            return symbol(sym.LBRACE,"{");
            }
          case 79: break;
          case 19: 
            { System.out.println(" RBRACE ");
                            return symbol(sym.RBRACE,"}");
            }
          case 80: break;
          case 20: 
            { System.out.println(" COMMA ");
                            return symbol(sym.COMMA,",");
            }
          case 81: break;
          case 21: 
            { System.out.println(" SEMICOLON ");
                            return symbol(sym.SEMICOLON,";");
            }
          case 82: break;
          case 22: 
            { System.out.println(" COLON ");
                            return symbol(sym.COLON,":");
            }
          case 83: break;
          case 23: 
            { string = string.concat(yytext());
            }
          case 84: break;
          case 24: 
            { yybegin(YYINITIAL); string.concat(yytext()); 
                            lexeme = lexema(ERROR,string); return symbol(sym.error);
            }
          case 85: break;
          case 25: 
            { yybegin(YYINITIAL);string = string.concat(yytext());
                            System.out.println(" LITERAL STRING ");    
                            lexeme = lexema(LITERAL_STRING,string); return symbol(sym.LITERAL_STRING);
            }
          case 86: break;
          case 26: 
            { System.out.println(" TEXTO_DIRECTIVA ");
                            return symbol(sym.TEXTO_DIRECTIVA,"texto_directiva");
            }
          case 87: break;
          case 27: 
            { System.out.println("MENOREQ");
                            return symbol(sym.MENOREQ,"<=");
            }
          case 88: break;
          case 28: 
            { System.out.println("MAYOREQ");
                            return symbol(sym.MAYOREQ,">=");
            }
          case 89: break;
          case 29: 
            { System.out.println("MINUSMINUS");
                            return symbol(sym.MINUSMINUS,"--");
            }
          case 90: break;
          case 30: 
            { System.out.println("MINUSEQ");
                            return symbol(sym.MINUSEQ,"-=");
            }
          case 91: break;
          case 31: 
            { System.out.println(" DOWHILE ");
                            return symbol(sym.DO,"do");
            }
          case 92: break;
          case 32: 
            { System.out.println(" IF ");
                            return symbol(sym.IF,"if");
            }
          case 93: break;
          case 33: 
            { System.out.println("||");
                            return symbol(sym.OR,"||");
            }
          case 94: break;
          case 34: 
            { System.out.println("&&");
                            return symbol(sym.AND,"&&");
            }
          case 95: break;
          case 35: 
            { System.out.println("PLUSPLUS");
                            return symbol(sym.PLUSPLUS,"++");
            }
          case 96: break;
          case 36: 
            { System.out.println("PLUSEQ");
                            return symbol(sym.PLUSEQ,"+=");
            }
          case 97: break;
          case 37: 
            { System.out.println("MODEQ");
                            return symbol(sym.MODEQ,"%=");
            }
          case 98: break;
          case 38: 
            { System.out.println(" NOTEQ ");
                            return symbol(sym.NOTEQ,"!");
            }
          case 99: break;
          case 39: 
            { System.out.println("TIMESEQ");
                            return symbol(sym.TIMESEQ,"*=");
            }
          case 100: break;
          case 40: 
            { yybegin(COMENTARIO_STATE);
            }
          case 101: break;
          case 41: 
            { System.out.println("DIVEQ");
                            return symbol(sym.DIVEQ,"/=");
            }
          case 102: break;
          case 42: 
            { System.out.println(" EQUAL ");
                            return symbol(sym.EQUAL,"==");
            }
          case 103: break;
          case 43: 
            { System.out.println(" CARACTER_C "); 
                            lexeme= lexema(LITERAL_CARACTER,yytext()); 
                            return symbol(sym.LITERAL_CARACTER, yytext());
            }
          case 104: break;
          case 44: 
            { System.out.println(" FOR ");
                            return symbol(sym.FOR,"for");
            }
          case 105: break;
          case 45: 
            { System.out.println(" INT ");
                            return symbol(sym.INT,"int");
            }
          case 106: break;
          case 46: 
            { System.out.println(" LONG ");
                            return symbol(sym.LONG,"long");
            }
          case 107: break;
          case 47: 
            { System.out.println(" ELSE ");
                            return symbol(sym.ELSE,"else");
            }
          case 108: break;
          case 48: 
            { System.out.println(" CASE ");
                            return symbol(sym.CASE,"case");
            }
          case 109: break;
          case 49: 
            { System.out.println(" CHAR ");
                            return symbol(sym.CHAR,"char");
            }
          case 110: break;
          case 50: 
            { System.out.println(" READ ");
                            return symbol(sym.READ,"read");
            }
          case 111: break;
          case 51: 
            { System.out.println(" VOID ");
                            return symbol(sym.VOID,"void");
            }
          case 112: break;
          case 52: 
            { System.out.println(" SHORT ");
                            return symbol(sym.SHORT,"short");
            }
          case 113: break;
          case 53: 
            { System.out.println(" CONST ");
                            return symbol(sym.CONST,"const");
            }
          case 114: break;
          case 54: 
            { System.out.println(" BREAK ");
                            return symbol(sym.BREAK,"break");
            }
          case 115: break;
          case 55: 
            { System.out.println(" WRITE ");
                            return symbol(sym.WRITE,"write");
            }
          case 116: break;
          case 56: 
            { System.out.println(" WHILE ");
                            return symbol(sym.WHILE,"while");
            }
          case 117: break;
          case 57: 
            { System.out.println(" SWITCH ");
                            return symbol(sym.SWITCH,"switch");
            }
          case 118: break;
          case 58: 
            { System.out.println(" RETURN ");
                            return symbol(sym.RETURN,"return");
            }
          case 119: break;
          case 59: 
            { System.out.println(" DEFAULT ");
                            return symbol(sym.DEFAULT,"default");
            }
          case 120: break;
          case 60: 
            { System.out.println(" INCLUDE ");
                            return symbol(sym.INCLUDE,"include");
            }
          case 121: break;
          case 61: 
            { System.out.println(" CONTINUE ");
                            return symbol(sym.CONTINUE,"continue");
            }
          case 122: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
