
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 22 21:15:56 CST 2015
//----------------------------------------------------

package parser.data;

import java_cup.runtime.*;
import java.util.ArrayList;
import java.io.FileReader;
import java.io.*;
import parser.controller.DatosArchivoController;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Jun 22 21:15:56 CST 2015
  */
public class Parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\146\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\056\002\000\002\003\007\000\002\057\002" +
    "\000\002\003\007\000\002\003\002\000\002\052\006\000" +
    "\002\042\003\000\002\043\003\000\002\044\003\000\002" +
    "\055\003\000\002\045\003\000\002\031\003\000\002\031" +
    "\003\000\002\004\005\000\002\005\005\000\002\060\002" +
    "\000\002\005\007\000\002\011\005\000\002\011\004\000" +
    "\002\011\003\000\002\012\005\000\002\012\004\000\002" +
    "\061\002\000\002\012\005\000\002\013\004\000\002\013" +
    "\003\000\002\014\003\000\002\014\003\000\002\014\003" +
    "\000\002\014\004\000\002\014\004\000\002\014\003\000" +
    "\002\015\003\000\002\015\004\000\002\015\003\000\002" +
    "\016\005\000\002\020\003\000\002\017\005\000\002\017" +
    "\005\000\002\017\005\000\002\017\007\000\002\017\007" +
    "\000\002\017\004\000\002\017\003\000\002\021\005\000" +
    "\002\021\003\000\002\021\003\000\002\026\005\000\002" +
    "\026\005\000\002\026\003\000\002\037\003\000\002\006" +
    "\006\000\002\006\005\000\002\062\002\000\002\006\007" +
    "\000\002\007\006\000\002\063\002\000\002\007\007\000" +
    "\002\010\005\000\002\010\003\000\002\022\010\000\002" +
    "\064\002\000\002\022\011\000\002\065\002\000\002\022" +
    "\007\000\002\066\002\000\002\022\010\000\002\050\003" +
    "\000\002\046\003\000\002\047\003\000\002\024\004\000" +
    "\002\024\002\000\002\051\003\000\002\023\007\000\002" +
    "\067\002\000\002\023\010\000\002\070\002\000\002\023" +
    "\007\000\002\071\002\000\002\023\007\000\002\053\003" +
    "\000\002\054\003\000\002\025\005\000\002\032\004\000" +
    "\002\032\004\000\002\032\002\000\002\036\003\000\002" +
    "\036\003\000\002\036\003\000\002\036\003\000\002\036" +
    "\003\000\002\036\003\000\002\035\003\000\002\035\003" +
    "\000\002\034\003\000\002\034\003\000\002\027\003\000" +
    "\002\027\003\000\002\027\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\251\000\010\002\ufffa\045\007\050\011\001\002\000" +
    "\004\053\250\001\002\000\010\002\ufffa\045\007\050\011" +
    "\001\002\000\004\053\016\001\002\000\004\053\ufff7\001" +
    "\002\000\004\002\013\001\002\000\004\053\ufff8\001\002" +
    "\000\004\002\000\001\002\000\004\002\001\001\002\000" +
    "\004\021\115\001\002\000\006\013\020\025\uffa9\001\002" +
    "\000\010\013\ufff6\021\ufff5\025\ufff6\001\002\000\004\025" +
    "\112\001\002\000\022\003\035\005\026\021\036\040\024" +
    "\046\022\047\034\051\033\053\037\001\002\000\004\025" +
    "\ufff4\001\002\000\004\021\103\001\002\000\014\022\uffd1" +
    "\025\uffd1\027\uffd1\042\uffd1\043\uffd1\001\002\000\012\005" +
    "\026\021\036\051\033\053\101\001\002\000\014\022\uffdc" +
    "\025\uffdc\027\uffdc\042\uffdc\043\uffdc\001\002\000\004\051" +
    "\100\001\002\000\014\022\uffde\025\uffde\027\uffde\042\uffde" +
    "\043\uffde\001\002\000\040\004\051\005\044\011\071\012" +
    "\075\022\uffd3\025\uffd3\027\uffd3\033\047\034\046\035\055" +
    "\036\050\037\052\041\045\042\uffd3\043\uffd3\001\002\000" +
    "\014\022\uffd0\025\uffd0\027\uffd0\042\uffd0\043\uffd0\001\002" +
    "\000\004\025\uffab\001\002\000\040\004\uff9d\005\uff9d\011" +
    "\uff9d\012\uff9d\022\uff9d\025\uff9d\027\uff9d\033\uff9d\034\uff9d" +
    "\035\uff9d\036\uff9d\037\uff9d\041\uff9d\042\uff9d\043\uff9d\001" +
    "\002\000\004\021\060\001\002\000\004\025\uffaa\001\002" +
    "\000\020\005\026\021\036\040\024\046\022\047\034\051" +
    "\033\053\037\001\002\000\042\004\uff9e\005\uff9e\011\uff9e" +
    "\012\uff9e\021\040\022\uff9e\025\uff9e\027\uff9e\033\uff9e\034" +
    "\uff9e\035\uff9e\036\uff9e\037\uff9e\041\uff9e\042\uff9e\043\uff9e" +
    "\001\002\000\004\022\041\001\002\000\014\022\uffd2\025" +
    "\uffd2\027\uffd2\042\uffd2\043\uffd2\001\002\000\004\022\043" +
    "\001\002\000\034\004\051\005\044\022\uffd7\025\uffd7\027" +
    "\uffd7\033\047\034\046\035\055\036\050\037\052\041\045" +
    "\042\uffd7\043\uffd7\001\002\000\020\005\uffa1\021\uffa1\040" +
    "\uffa1\046\uffa1\047\uffa1\051\uffa1\053\uffa1\001\002\000\020" +
    "\005\uffa7\021\uffa7\040\uffa7\046\uffa7\047\uffa7\051\uffa7\053" +
    "\uffa7\001\002\000\020\005\uffa4\021\uffa4\040\uffa4\046\uffa4" +
    "\047\uffa4\051\uffa4\053\uffa4\001\002\000\020\005\uffa8\021" +
    "\uffa8\040\uffa8\046\uffa8\047\uffa8\051\uffa8\053\uffa8\001\002" +
    "\000\020\005\uffa3\021\uffa3\040\uffa3\046\uffa3\047\uffa3\051" +
    "\uffa3\053\uffa3\001\002\000\020\005\uffa2\021\uffa2\040\uffa2" +
    "\046\uffa2\047\uffa2\051\uffa2\053\uffa2\001\002\000\020\005" +
    "\uffa5\021\uffa5\040\uffa5\046\uffa5\047\uffa5\051\uffa5\053\uffa5" +
    "\001\002\000\020\005\026\021\036\040\024\046\022\047" +
    "\034\051\033\053\037\001\002\000\020\005\026\021\036" +
    "\040\024\046\022\047\034\051\033\053\037\001\002\000" +
    "\020\005\uffa6\021\uffa6\040\uffa6\046\uffa6\047\uffa6\051\uffa6" +
    "\053\uffa6\001\002\000\014\022\uffd6\025\uffd6\027\uffd6\042" +
    "\uffd6\043\uffd6\001\002\000\014\022\uffd5\025\uffd5\027\uffd5" +
    "\042\uffd5\043\uffd5\001\002\000\022\003\063\005\026\021" +
    "\036\040\024\046\022\047\034\051\033\053\037\001\002" +
    "\000\006\022\uffc3\027\uffc3\001\002\000\006\022\067\027" +
    "\066\001\002\000\004\022\uffc6\001\002\000\004\022\065" +
    "\001\002\000\014\022\uffc5\025\uffc5\027\uffc5\042\uffc5\043" +
    "\uffc5\001\002\000\020\005\026\021\036\040\024\046\022" +
    "\047\034\051\033\053\037\001\002\000\014\022\uffc7\025" +
    "\uffc7\027\uffc7\042\uffc7\043\uffc7\001\002\000\006\022\uffc4" +
    "\027\uffc4\001\002\000\014\022\uffa0\025\uffa0\027\uffa0\042" +
    "\uffa0\043\uffa0\001\002\000\014\022\uffd4\025\uffd4\027\uffd4" +
    "\042\uffd4\043\uffd4\001\002\000\020\005\026\021\036\040" +
    "\024\046\022\047\034\051\033\053\037\001\002\000\020" +
    "\005\026\021\036\040\024\046\022\047\034\051\033\053" +
    "\037\001\002\000\014\022\uff9f\025\uff9f\027\uff9f\042\uff9f" +
    "\043\uff9f\001\002\000\014\022\uffd9\025\uffd9\027\uffd9\042" +
    "\uffd9\043\uffd9\001\002\000\014\022\uffd8\025\uffd8\027\uffd8" +
    "\042\uffd8\043\uffd8\001\002\000\040\004\uff9c\005\uff9c\011" +
    "\uff9c\012\uff9c\022\uff9c\025\uff9c\027\uff9c\033\uff9c\034\uff9c" +
    "\035\uff9c\036\uff9c\037\uff9c\041\uff9c\042\uff9c\043\uff9c\001" +
    "\002\000\040\004\uff9e\005\uff9e\011\uff9e\012\uff9e\022\uff9e" +
    "\025\uff9e\027\uff9e\033\uff9e\034\uff9e\035\uff9e\036\uff9e\037" +
    "\uff9e\041\uff9e\042\uff9e\043\uff9e\001\002\000\014\022\uffdd" +
    "\025\uffdd\027\uffdd\042\uffdd\043\uffdd\001\002\000\010\003" +
    "\105\022\104\053\106\001\002\000\014\022\uffca\025\uffca" +
    "\027\uffca\042\uffca\043\uffca\001\002\000\004\022\uffc9\001" +
    "\002\000\004\022\107\001\002\000\014\022\uffcb\025\uffcb" +
    "\027\uffcb\042\uffcb\043\uffcb\001\002\000\004\022\111\001" +
    "\002\000\014\022\uffc8\025\uffc8\027\uffc8\042\uffc8\043\uffc8" +
    "\001\002\000\036\002\ufff9\005\ufff9\021\ufff9\024\ufff9\030" +
    "\ufff9\032\ufff9\040\ufff9\044\ufff9\045\ufff9\046\ufff9\047\ufff9" +
    "\050\ufff9\051\ufff9\053\ufff9\001\002\000\010\002\ufffc\045" +
    "\ufffc\050\ufffc\001\002\000\010\002\ufff2\045\ufff2\050\ufff2" +
    "\001\002\000\006\003\120\022\117\001\002\000\010\002" +
    "\ufff3\045\ufff3\050\ufff3\001\002\000\010\003\124\023\123" +
    "\025\242\001\002\000\004\022\uffef\001\002\000\004\022" +
    "\122\001\002\000\006\003\124\023\123\001\002\000\032" +
    "\005\026\021\036\024\126\030\135\032\130\040\024\044" +
    "\134\046\022\047\034\050\011\051\033\053\144\001\002" +
    "\000\010\002\uffeb\045\uffeb\050\uffeb\001\002\000\010\002" +
    "\uffee\045\uffee\050\uffee\001\002\000\010\002\uffec\045\uffec" +
    "\050\uffec\001\002\000\032\005\uffe4\021\uffe4\024\uffe4\030" +
    "\uffe4\032\uffe4\040\uffe4\044\uffe4\046\uffe4\047\uffe4\050\uffe4" +
    "\051\uffe4\053\uffe4\001\002\000\006\003\uffae\021\uffae\001" +
    "\002\000\032\005\026\021\036\024\241\030\135\032\130" +
    "\040\024\044\134\046\022\047\034\050\011\051\033\053" +
    "\144\001\002\000\004\025\240\001\002\000\032\005\uffe2" +
    "\021\uffe2\024\uffe2\030\uffe2\032\uffe2\040\uffe2\044\uffe2\046" +
    "\uffe2\047\uffe2\050\uffe2\051\uffe2\053\uffe2\001\002\000\020" +
    "\005\026\021\036\040\024\046\022\047\034\051\033\053" +
    "\037\001\002\000\006\003\uffbb\021\uffbb\001\002\000\004" +
    "\053\235\001\002\000\004\025\234\001\002\000\006\003" +
    "\207\021\210\001\002\000\032\005\uffe5\021\uffe5\024\uffe5" +
    "\030\uffe5\032\uffe5\040\uffe5\044\uffe5\046\uffe5\047\uffe5\050" +
    "\uffe5\051\uffe5\053\uffe5\001\002\000\032\005\uffdf\021\uffdf" +
    "\024\uffdf\030\uffdf\032\uffdf\040\uffdf\044\uffdf\046\uffdf\047" +
    "\uffdf\050\uffdf\051\uffdf\053\uffdf\001\002\000\032\005\uffe3" +
    "\021\uffe3\024\uffe3\030\uffe3\032\uffe3\040\uffe3\044\uffe3\046" +
    "\uffe3\047\uffe3\050\uffe3\051\uffe3\053\uffe3\001\002\000\034" +
    "\004\uff9e\005\uff9e\011\uff9e\012\uff9e\013\205\021\040\025" +
    "\uff9e\033\uff9e\034\uff9e\035\uff9e\036\uff9e\037\uff9e\041\uff9e" +
    "\001\002\000\006\003\146\021\147\001\002\000\004\022" +
    "\uffb0\001\002\000\022\003\153\005\026\021\036\040\024" +
    "\046\022\047\034\051\033\053\037\001\002\000\010\022" +
    "\uffcd\042\176\043\175\001\002\000\010\022\uffcc\042\uffcc" +
    "\043\uffcc\001\002\000\004\022\uffba\001\002\000\010\003" +
    "\uffb2\022\uffb4\023\uffb2\001\002\000\004\022\155\001\002" +
    "\000\006\003\uffad\023\uffad\001\002\000\006\003\160\023" +
    "\157\001\002\000\032\005\026\021\036\024\164\030\135" +
    "\032\130\040\024\044\134\046\022\047\034\050\011\051" +
    "\033\053\144\001\002\000\002\001\002\000\032\005\uffb5" +
    "\021\uffb5\024\uffb5\030\uffb5\032\uffb5\040\uffb5\044\uffb5\046" +
    "\uffb5\047\uffb5\050\uffb5\051\uffb5\053\uffb5\001\002\000\002" +
    "\001\002\000\034\005\uffe7\021\uffe7\024\uffe7\030\uffe7\031" +
    "\uffe7\032\uffe7\040\uffe7\044\uffe7\046\uffe7\047\uffe7\050\uffe7" +
    "\051\uffe7\053\uffe7\001\002\000\034\005\uffe9\021\uffe9\024" +
    "\uffe9\030\uffe9\031\uffe9\032\uffe9\040\uffe9\044\uffe9\046\uffe9" +
    "\047\uffe9\050\uffe9\051\uffe9\053\uffe9\001\002\000\032\005" +
    "\026\021\036\024\166\030\135\032\130\040\024\044\134" +
    "\046\022\047\034\050\011\051\033\053\144\001\002\000" +
    "\034\005\uffea\021\uffea\024\uffea\030\uffea\031\uffea\032\uffea" +
    "\040\uffea\044\uffea\046\uffea\047\uffea\050\uffea\051\uffea\053" +
    "\uffea\001\002\000\032\005\uffe6\021\uffe6\024\uffe6\030\uffe6" +
    "\032\uffe6\040\uffe6\044\uffe6\046\uffe6\047\uffe6\050\uffe6\051" +
    "\uffe6\053\uffe6\001\002\000\006\003\160\023\157\001\002" +
    "\000\004\022\172\001\002\000\006\003\160\023\157\001" +
    "\002\000\032\005\uffb3\021\uffb3\024\uffb3\030\uffb3\032\uffb3" +
    "\040\uffb3\044\uffb3\046\uffb3\047\uffb3\050\uffb3\051\uffb3\053" +
    "\uffb3\001\002\000\032\005\uffb1\021\uffb1\024\uffb1\030\uffb1" +
    "\032\uffb1\040\uffb1\044\uffb1\046\uffb1\047\uffb1\050\uffb1\051" +
    "\uffb1\053\uffb1\001\002\000\020\005\026\021\036\040\024" +
    "\046\022\047\034\051\033\053\037\001\002\000\020\005" +
    "\026\021\036\040\024\046\022\047\034\051\033\053\037" +
    "\001\002\000\004\022\uffce\001\002\000\004\022\uffcf\001" +
    "\002\000\004\022\202\001\002\000\006\003\160\023\157" +
    "\001\002\000\032\005\uffaf\021\uffaf\024\uffaf\030\uffaf\032" +
    "\uffaf\040\uffaf\044\uffaf\046\uffaf\047\uffaf\050\uffaf\051\uffaf" +
    "\053\uffaf\001\002\000\020\005\026\021\036\040\024\046" +
    "\022\047\034\051\033\053\037\001\002\000\020\005\uffda" +
    "\021\uffda\040\uffda\046\uffda\047\uffda\051\uffda\053\uffda\001" +
    "\002\000\004\025\uffdb\001\002\000\004\022\uffbd\001\002" +
    "\000\022\003\211\005\026\021\036\040\024\046\022\047" +
    "\034\051\033\053\037\001\002\000\010\003\uffbf\022\uffc1" +
    "\023\uffbf\001\002\000\004\022\214\001\002\000\006\003" +
    "\160\023\157\001\002\000\006\003\uffb9\023\uffb9\001\002" +
    "\000\034\005\uffb7\021\uffb7\024\uffb7\030\uffb7\031\217\032" +
    "\uffb7\040\uffb7\044\uffb7\046\uffb7\047\uffb7\050\uffb7\051\uffb7" +
    "\053\uffb7\001\002\000\006\003\160\023\157\001\002\000" +
    "\006\003\uffb6\023\uffb6\001\002\000\032\005\uffc2\021\uffc2" +
    "\024\uffc2\030\uffc2\032\uffc2\040\uffc2\044\uffc2\046\uffc2\047" +
    "\uffc2\050\uffc2\051\uffc2\053\uffc2\001\002\000\032\005\uffb8" +
    "\021\uffb8\024\uffb8\030\uffb8\032\uffb8\040\uffb8\044\uffb8\046" +
    "\uffb8\047\uffb8\050\uffb8\051\uffb8\053\uffb8\001\002\000\006" +
    "\003\160\023\157\001\002\000\004\022\224\001\002\000" +
    "\006\003\160\023\157\001\002\000\034\005\uffb7\021\uffb7" +
    "\024\uffb7\030\uffb7\031\217\032\uffb7\040\uffb7\044\uffb7\046" +
    "\uffb7\047\uffb7\050\uffb7\051\uffb7\053\uffb7\001\002\000\032" +
    "\005\uffc0\021\uffc0\024\uffc0\030\uffc0\032\uffc0\040\uffc0\044" +
    "\uffc0\046\uffc0\047\uffc0\050\uffc0\051\uffc0\053\uffc0\001\002" +
    "\000\032\005\uffbe\021\uffbe\024\uffbe\030\uffbe\032\uffbe\040" +
    "\uffbe\044\uffbe\046\uffbe\047\uffbe\050\uffbe\051\uffbe\053\uffbe" +
    "\001\002\000\004\022\231\001\002\000\006\003\160\023" +
    "\157\001\002\000\034\005\uffb7\021\uffb7\024\uffb7\030\uffb7" +
    "\031\217\032\uffb7\040\uffb7\044\uffb7\046\uffb7\047\uffb7\050" +
    "\uffb7\051\uffb7\053\uffb7\001\002\000\032\005\uffbc\021\uffbc" +
    "\024\uffbc\030\uffbc\032\uffbc\040\uffbc\044\uffbc\046\uffbc\047" +
    "\uffbc\050\uffbc\051\uffbc\053\uffbc\001\002\000\032\005\uffe0" +
    "\021\uffe0\024\uffe0\030\uffe0\032\uffe0\040\uffe0\044\uffe0\046" +
    "\uffe0\047\uffe0\050\uffe0\051\uffe0\053\uffe0\001\002\000\006" +
    "\013\ufff6\025\ufff6\001\002\000\004\025\237\001\002\000" +
    "\032\005\uffac\021\uffac\024\uffac\030\uffac\032\uffac\040\uffac" +
    "\044\uffac\046\uffac\047\uffac\050\uffac\051\uffac\053\uffac\001" +
    "\002\000\032\005\uffe1\021\uffe1\024\uffe1\030\uffe1\032\uffe1" +
    "\040\uffe1\044\uffe1\046\uffe1\047\uffe1\050\uffe1\051\uffe1\053" +
    "\uffe1\001\002\000\010\002\uffed\045\uffed\050\uffed\001\002" +
    "\000\010\002\ufff1\045\ufff1\050\ufff1\001\002\000\010\002" +
    "\ufff0\045\ufff0\050\ufff0\001\002\000\010\002\ufffa\045\007" +
    "\050\011\001\002\000\004\002\ufffb\001\002\000\004\002" +
    "\uffff\001\002\000\004\021\115\001\002\000\004\021\ufff5" +
    "\001\002\000\010\002\ufffe\045\ufffe\050\ufffe\001\002\000" +
    "\010\002\ufffa\045\007\050\011\001\002\000\004\002\ufffd" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\251\000\014\002\007\003\011\042\005\043\003\052" +
    "\004\001\001\000\004\055\246\001\001\000\012\003\245" +
    "\042\005\043\003\052\004\001\001\000\006\044\014\055" +
    "\013\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\004" +
    "\115\005\113\031\112\001\001\000\006\032\020\045\016" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\006" +
    "\022\007\030\015\031\017\026\021\024\027\027\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\017\101\027\027\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\034\071\035\073\036" +
    "\072\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\006" +
    "\022\007\030\015\041\017\026\021\024\027\027\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\035\053\036\052\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\016\006\022\007\030\015\056\017\026\021\024\027" +
    "\027\001\001\000\016\006\022\007\030\015\055\017\026" +
    "\021\024\027\027\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\020\006\022\007\030\010\061" +
    "\015\060\017\026\021\024\027\027\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\063\063\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\006\022\007\030\015" +
    "\067\017\026\021\024\027\027\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\016\006\022\007\030\015\076\017\026\021\024\027\027" +
    "\001\001\000\016\006\022\007\030\015\075\017\026\021" +
    "\024\027\027\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\062\107\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\057\243\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\011\242\001\001\000\004\060\120" +
    "\001\001\000\002\001\001\000\004\011\124\001\001\000" +
    "\042\006\022\007\030\013\130\014\140\015\131\016\136" +
    "\017\026\021\024\022\126\023\132\025\141\027\027\042" +
    "\135\050\137\052\142\053\144\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\040\006\022\007\030\014\166\015\131" +
    "\016\136\017\026\021\024\022\126\023\132\025\141\027" +
    "\027\042\135\050\137\052\142\053\144\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\006\022\007\030\015" +
    "\235\017\026\021\024\027\027\001\001\000\002\001\001" +
    "\000\004\044\014\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\020\203\001\001\000\002\001\001\000\004\071" +
    "\200\001\001\000\024\006\022\007\030\015\150\017\026" +
    "\021\024\026\151\027\027\037\147\046\153\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\067\170\070\167\001\001\000\004\054\155\001\001\000" +
    "\002\001\001\000\004\012\160\001\001\000\042\006\022" +
    "\007\030\013\164\014\140\015\131\016\136\017\026\021" +
    "\024\022\126\023\132\025\141\027\027\042\135\050\137" +
    "\052\142\053\144\001\001\000\004\061\161\001\001\000" +
    "\002\001\001\000\004\030\162\001\001\000\002\001\001" +
    "\000\002\001\001\000\040\006\022\007\030\014\166\015" +
    "\131\016\136\017\026\021\024\022\126\023\132\025\141" +
    "\027\027\042\135\050\137\052\142\053\144\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\012\173\001\001" +
    "\000\002\001\001\000\004\012\172\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\006\022\007\030\015\150" +
    "\017\026\021\024\026\177\027\027\037\147\001\001\000" +
    "\022\006\022\007\030\015\150\017\026\021\024\026\176" +
    "\027\027\037\147\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\012\202\001\001\000\002" +
    "\001\001\000\016\006\022\007\030\015\205\017\026\021" +
    "\024\027\027\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\066\227\001\001\000\024\006\022\007\030\015" +
    "\150\017\026\021\024\026\151\027\027\037\147\046\211" +
    "\001\001\000\006\064\222\065\221\001\001\000\004\047" +
    "\212\001\001\000\004\012\214\001\001\000\002\001\001" +
    "\000\006\024\217\051\215\001\001\000\004\012\220\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\012\226\001\001\000\002\001\001\000\004\012" +
    "\224\001\001\000\006\024\225\051\215\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\012" +
    "\231\001\001\000\006\024\232\051\215\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\003\244\042" +
    "\005\043\003\052\004\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\004\115\005\113\031\250\001\001\000" +
    "\002\001\001\000\004\056\251\001\001\000\012\003\252" +
    "\042\005\043\003\052\004\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public static Lexer s;
    public static int errors = 0;
    public static ErrorData errorData = ErrorData.getInstance();
    public DatosArchivoController archivoController = DatosArchivoController.getInstance();
    ErrorData detectedError;
    public TablaSimbolos tablaSimbolos = new TablaSimbolos();
    public PilaSemantica pilaSemantica = new PilaSemantica();
    String assemblyFile = "";
    
    /* Reporte de error encontrado. */

    public void report_error(String message,int line, int column) {
        StringBuilder m = new StringBuilder("Error");
        m.append(" en la línea "+(line+1));
        m.append(", columna "+(column+1));
        m.append(" : " + message);
        archivoController.mostrarErroresSemanticos(m.toString());
    }
    public void report_error(String message, Object info) {
        if (info instanceof String){
            errors++;
            String mensaje = ", se esperaba: " + message;
            try{
                detectedError.setId(errors);
            }catch(Exception e){
                detectedError = new ErrorData(errors, info.toString(), mensaje);
            }
            detectedError.setMessage(detectedError.getMessage() + mensaje);
            errorData.insertarError(detectedError);
        }
        else {
            StringBuilder m = new StringBuilder("Error");
            if (info instanceof java_cup.runtime.Symbol) {
                java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
                if (s.left >= 0) {                
                    m.append(" en la línea "+(s.left+1));
                    if (s.right >= 0)
                        m.append(", columna "+(s.right+1));
                }
            }
            m.append(" : " + message);
            detectedError = new ErrorData(errors, info.toString(), m.toString());
        }
    }
   
    /* Cuando se encuentra un error de donde el sistema no puede
        recuperarse, se lanza un error fatal. Se despliega el mensaje
        de error y se finaliza la ejecucion. */
    public void report_fatal_error(String message, Object info) {
        System.out.println("----------FUI YO------------");
        report_error(message, info);
        System.exit(1);
    }

    /* Metodo main para garantizar la ejecucion del analizador
       lexico y sintactico, ademas que se pase como parametro la tabla
       de simbolos correspondiente. */
    public static void main(String[] args){
        try {
            s = new Lexer(new FileReader(args[0]));
            Parser p = new Parser(s);
            p.parse();
            System.out.println("\n*** Fin del parseo ***");
            System.out.println(p.assemblyFile);
            File archivo = p.archivoController.getArchivoFromData();
            String newArchivo = archivo.getName().replace(".c", "");
            PrintWriter writer = new PrintWriter(newArchivo + ".asm", "UTF-8");
            writer.println("section .text\n\tglobal _start\n_start:  ");
            writer.println(p.assemblyFile);

            writer.println("\tmov eax, 1");
            writer.println("\tmov ebx, 0");
            writer.println("\tint 80h");

            //Section .data
            writer.println("\nsection     .data\n");
            ArrayList<String> TS = p.tablaSimbolos.getTempVars();
            for(int i = 0; i < TS.size(); i++){
                writer.println("\t" + TS.get(i) + ":    resb 1");
            }

            
            writer.close();

            System.out.println("Total de errores = " + errors + ".");
            errors = 0;
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 101: // valor ::= SUBSTRACT LITERAL_ENTERO 
            {
              Object RESULT =null;
		int litleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int litright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer lit = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = lit; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // valor ::= LITERAL_ENTERO 
            {
              Object RESULT =null;
		int litleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int litright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer lit = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		  System.out.println("---------------CREADO-LIT---------------");
                                RegistroSemanticoVar RS_DO = new RegistroSemanticoVar("RS_DO_C",lit.toString());
                                parser.pilaSemantica.push(RS_DO);
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // valor ::= IDENTIFICADOR 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		  RegistroSemanticoVar RS_DO = new RegistroSemanticoVar("RS_DO_D",i.toString());
                                System.out.println("---------------CREADO-"+i.toString()+"---------------");
                                if( parser.tablaSimbolos.get(RS_DO.getToken()) ==null){
                                    parser.report_error(" Variable '" + RS_DO.getToken() + "' no ha sido declarado.", ileft,iright); 
                                }
                                RS_DO.setValor(parser.tablaSimbolos.get(RS_DO.getToken()).getDireccion());
                                RS_DO.setDireccion(parser.tablaSimbolos.get(RS_DO.getToken()).getDireccion());
                                parser.pilaSemantica.push(RS_DO);
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // operacion_bin_1 ::= MINUSMINUS 
            {
              Object RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RegistroSemantico RS_OP = new RegistroSemantico(p.toString(),"MenosMenos");
                               parser.pilaSemantica.push(RS_OP);
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operacion_bin_1",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // operacion_bin_1 ::= PLUSPLUS 
            {
              Object RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RegistroSemantico RS_OP = new RegistroSemantico(op.toString(),"MasMas");
                               parser.pilaSemantica.push(RS_OP);
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operacion_bin_1",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // operador ::= SUBSTRACT 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RegistroSemantico RS_OP = new RegistroSemantico(s.toString(),"Resta");
                               parser.pilaSemantica.push(RS_OP);
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operador",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // operador ::= ADD 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RegistroSemantico RS_OP = new RegistroSemantico(a.toString(),"Suma");
                               parser.pilaSemantica.push(RS_OP);
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operador",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // comparador ::= MAYORQUE 
            {
              Object RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RegistroSemantico RS_OP = new RegistroSemantico(op.toString(),"Mayor");
                               parser.pilaSemantica.push(RS_OP);
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparador",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // comparador ::= MENORQUE 
            {
              Object RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RegistroSemantico RS_OP = new RegistroSemantico(op.toString(),"Menor");
                               parser.pilaSemantica.push(RS_OP);
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparador",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // comparador ::= MAYOREQ 
            {
              Object RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RegistroSemantico RS_OP = new RegistroSemantico(op.toString(),"MayorIgual");
                               parser.pilaSemantica.push(RS_OP);
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparador",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // comparador ::= MENOREQ 
            {
              Object RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RegistroSemantico RS_OP = new RegistroSemantico(op.toString(),"MenorIgual");
                               parser.pilaSemantica.push(RS_OP);
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparador",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // comparador ::= NOTEQ 
            {
              Object RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RegistroSemantico RS_OP = new RegistroSemantico(op.toString(),"NoIgual");
                               parser.pilaSemantica.push(RS_OP);
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparador",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // comparador ::= EQUAL 
            {
              Object RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RegistroSemantico RS_OP = new RegistroSemantico(op.toString(),"Igual");
                               parser.pilaSemantica.push(RS_OP);
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparador",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // validar_expr ::= 
            {
              Object RESULT =null;
		 RESULT = ""; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("validar_expr",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // validar_expr ::= ASSIGN error 
            {
              Object RESULT =null;
		 parser.report_error(" una expresión o falta ; al final.",""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("validar_expr",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // validar_expr ::= ASSIGN expresion 
            {
              Object RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object exp = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = exp; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("validar_expr",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // return_stmt ::= RETURN expresion SEMICOLON 
            {
              Object RESULT =null;
		
                                RegistroSemanticoVar RS_DO = (RegistroSemanticoVar) parser.pilaSemantica.pop();
                                parser.assemblyFile += "\tmov ax, " + RS_DO.getDireccion() + "\n";
                                parser.assemblyFile += "\tret\n"; 
                        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("return_stmt",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // test_while ::= RPAREN 
            {
              Object RESULT =null;
		
                                RegistroSemanticoVar RS_DO = (RegistroSemanticoVar)parser.pilaSemantica.pop();
                                parser.assemblyFile+= "\tmov eax,"+RS_DO.getDireccion()+" \n"; 
                                parser.assemblyFile+= "\tcmp eax, 0 \n"; 
                                parser.assemblyFile+= "\tJNZ "+ ((RegistroSemanticoSTMT)parser.pilaSemantica.searchRS("RS_WHILE")).getExit_label() +  "\n" ;
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("test_while",42, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // start_while ::= WHILE 
            {
              Object RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int wright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object w = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                RegistroSemanticoSTMT RS_WHILE = new RegistroSemanticoSTMT(w.toString(), "RS_WHILE");//Crear RS_WHILE
                                RS_WHILE.setStmt_label(parser.tablaSimbolos.getLabelName());
                                RS_WHILE.setExit_label(parser.tablaSimbolos.getLabelName());
                                parser.pilaSemantica.push(RS_WHILE);    
                                parser.assemblyFile += ((RegistroSemanticoSTMT)parser.pilaSemantica.searchRS("RS_WHILE")).getStmt_label()+": \n";
                                
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("start_while",41, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // while_statement ::= start_while error NT$11 RPAREN bloque 
            {
              Object RESULT =null;
              // propagate RESULT from NT$11
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("while_statement",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // NT$11 ::= 
            {
              Object RESULT =null;
 parser.report_error(" un LPAREN al final de la condición del WHILE.", ""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$11",55, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // while_statement ::= start_while LPAREN error NT$10 bloque 
            {
              Object RESULT =null;
              // propagate RESULT from NT$10
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("while_statement",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // NT$10 ::= 
            {
              Object RESULT =null;
 parser.report_error(" un RPAREN al final de la condición del WHILE.", ""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$10",54, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // while_statement ::= start_while LPAREN error NT$9 RPAREN bloque 
            {
              Object RESULT =null;
              // propagate RESULT from NT$9
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("while_statement",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // NT$9 ::= 
            {
              Object RESULT =null;
 parser.report_error("una condición valida para el WHILE.", ""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$9",53, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // while_statement ::= start_while LPAREN condicion_stmt test_while bloque 
            {
              Object RESULT =null;
		
                                parser.assemblyFile += "\tJMP "+((RegistroSemanticoSTMT)parser.pilaSemantica.searchRS("RS_WHILE")).getStmt_label()+" \n";
                                parser.assemblyFile += ((RegistroSemanticoSTMT)parser.pilaSemantica.searchRS("RS_WHILE")).getExit_label()+": \n";
                                parser.pilaSemantica.pop();
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("while_statement",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // else_stmt ::= ELSE 
            {
              Object RESULT =null;
		
                                     parser.assemblyFile += "\tJMP "+((RegistroSemanticoSTMT)parser.pilaSemantica.searchRS("RS_IF")).getExit_label()+" \n";
                                     parser.assemblyFile += ((RegistroSemanticoSTMT)parser.pilaSemantica.searchRS("RS_IF")).getStmt_label()+": \n";
                                 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("else_stmt",39, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // else_statement ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("else_statement",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // else_statement ::= else_stmt bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("else_statement",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // test_if ::= RPAREN 
            {
              Object RESULT =null;
		
                                    RegistroSemanticoVar RS_DO = (RegistroSemanticoVar)parser.pilaSemantica.pop();
                                    parser.assemblyFile+= "\tmov eax,"+RS_DO.getDireccion()+" \n"; 
                                    parser.assemblyFile+= "\tcmp eax, 0 \n"; 
                                    parser.assemblyFile+= "\tJNZ "+ ((RegistroSemanticoSTMT)parser.pilaSemantica.searchRS("RS_IF")).getStmt_label() +  "\n" ;
                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("test_if",37, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // condicion_stmt ::= condicion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_stmt",36, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // start_if ::= IF 
            {
              Object RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object tipo = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                    RegistroSemanticoSTMT RS_IF = new RegistroSemanticoSTMT(tipo.toString(), "RS_IF");//Crear RS_IF
                                    RS_IF.setStmt_label(parser.tablaSimbolos.getLabelName());
                                    RS_IF.setExit_label(parser.tablaSimbolos.getLabelName());
                                    parser.pilaSemantica.push(RS_IF);
                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("start_if",38, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // if_statement ::= start_if error NT$8 RPAREN bloque else_statement 
            {
              Object RESULT =null;
              // propagate RESULT from NT$8
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_statement",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // NT$8 ::= 
            {
              Object RESULT =null;
 parser.report_error(" un LPAREN al final de la condición del IF.", ""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$8",52, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // if_statement ::= start_if LPAREN error NT$7 bloque 
            {
              Object RESULT =null;
              // propagate RESULT from NT$7
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_statement",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // NT$7 ::= 
            {
              Object RESULT =null;
 parser.report_error(" un RPAREN al final de la condición del IF.", ""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$7",51, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // if_statement ::= start_if LPAREN error NT$6 RPAREN bloque else_statement 
            {
              Object RESULT =null;
              // propagate RESULT from NT$6
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_statement",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // NT$6 ::= 
            {
              Object RESULT =null;
 parser.report_error(" una condición válida para el IF.", ""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$6",50, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // if_statement ::= start_if LPAREN condicion_stmt test_if bloque else_statement 
            {
              Object RESULT =null;
		 
                                        parser.assemblyFile += ((RegistroSemanticoSTMT)parser.pilaSemantica.searchRS("RS_IF")).getExit_label()+": \n";
                                        RegistroSemantico a = parser.pilaSemantica.pop();
                                        System.out.println("**************" + a.getToken());
                                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_statement",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // write_f_aux ::= expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("write_f_aux",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // write_f_aux ::= write_f_aux COMMA expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("write_f_aux",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // write_f ::= WRITE LPAREN error NT$5 RPAREN 
            {
              Object RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("write_f",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // NT$5 ::= 
            {
              Object RESULT =null;
 parser.report_error(" parámetros incorrectos en el WRITE.", ""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$5",49, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // write_f ::= WRITE LPAREN write_f_aux RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("write_f",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // read_f ::= READ LPAREN error NT$4 RPAREN 
            {
              Object RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("read_f",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // NT$4 ::= 
            {
              Object RESULT =null;
 parser.report_error(" parámetros incorrectos en el READ.", ""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$4",48, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // read_f ::= READ LPAREN RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("read_f",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // read_f ::= READ LPAREN IDENTIFICADOR RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("read_f",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // condicion_2 ::= expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_2",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // condicion ::= condicion_2 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // condicion ::= condicion_2 OR condicion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // condicion ::= condicion_2 AND condicion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // call_function ::= write_f 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("call_function",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // call_function ::= read_f 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("call_function",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // call_function ::= IDENTIFICADOR LPAREN RPAREN 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 RESULT = i; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("call_function",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // exp ::= valor 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("exp",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // exp ::= valor operacion_bin_1 
            {
              Object RESULT =null;
		 
                               RegistroSemantico RS_OP= parser.pilaSemantica.pop();
                               RegistroSemantico RS_DO1= parser.pilaSemantica.pop();
                               String var = parser.tablaSimbolos.getVarName();
                               IOperacion op = (IOperacion)new OperacionFactory(RS_OP.getTipo()).getOp();
                               op.setOperandor(RS_DO1);
                               op.setVarReturn(var);
                               String code = op.generarCodigo();
                               parser.assemblyFile += code;
                               RegistroSemanticoVar RS_RESULT = new RegistroSemanticoVar(RS_DO1.getTipo(),var);
                               parser.pilaSemantica.push(RS_RESULT);
                               parser.tablaSimbolos.get(RS_DO1.getToken()).setDireccion(var);
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("exp",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // exp ::= LPAREN expresion RPAREN comparador expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("exp",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // exp ::= LPAREN expresion RPAREN operador expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("exp",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // exp ::= LPAREN expresion RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("exp",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // exp ::= valor comparador expresion 
            {
              Object RESULT =null;
		 
                                RegistroSemantico RS_DO1= parser.pilaSemantica.pop();
                                RegistroSemantico RS_OP= parser.pilaSemantica.pop();
                                RegistroSemantico RS_DO2= parser.pilaSemantica.pop();
                                String var = parser.tablaSimbolos.getVarName();
                                IOperacion op = (IOperacion)new OperacionFactory(RS_OP.getTipo()).getOp();
                                op.setOperandos(RS_DO1,RS_DO2);
                                op.setVarReturn(var);
                                String code = op.generarCodigo();
                                parser.assemblyFile += code;
                                RegistroSemanticoVar RS_RESULT = new RegistroSemanticoVar(RS_DO1.getTipo(),var);
                                parser.pilaSemantica.push(RS_RESULT);
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("exp",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // exp ::= valor operador expresion 
            {
              Object RESULT =null;
		 RegistroSemantico RS_DO1= parser.pilaSemantica.pop();
                               RegistroSemantico RS_OP= parser.pilaSemantica.pop();
                               RegistroSemantico RS_DO2= parser.pilaSemantica.pop();
                               System.out.println(RS_DO1.getValor());
                               String var = parser.tablaSimbolos.getVarName();
                               IOperacion op = (IOperacion)new OperacionFactory(RS_OP.getTipo()).getOp();
                               op.setOperandos(RS_DO1,RS_DO2);
                               op.setVarReturn(var);
                               String code = op.generarCodigo();
                               parser.assemblyFile += code;
                               RegistroSemanticoVar RS_RESULT = new RegistroSemanticoVar(RS_DO1.getTipo(),var);
                               parser.pilaSemantica.push(RS_RESULT);
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("exp",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // op_asignaciones ::= ASSIGN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("op_asignaciones",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // asignacion ::= IDENTIFICADOR op_asignaciones expresion 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
                                if( parser.tablaSimbolos.get(i.toString()) ==null){
                                    parser.report_error(" Variable '" + i.toString() + "' no ha sido declarada.", ileft,iright); 
                                }else{
                                    RegistroSemanticoVar RS_DO = (RegistroSemanticoVar) parser.pilaSemantica.pop();
                                    System.out.println("----********-----------------"+RS_DO.getDireccion()+"------------------");
                                    parser.tablaSimbolos.get(i.toString()).setDireccion(RS_DO.getDireccion());
                                }   
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expresion ::= call_function 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                    if( parser.tablaSimbolos.get(i.toString()) ==null){
                                        parser.report_error(" Función '" + i.toString() + "' no ha sido declarada.", ileft,iright); 
                                    }else{
                                        String tipo = parser.tablaSimbolos.get(i.toString()).getTipo();
                                        RegistroSemanticoVar RS_DO = new RegistroSemanticoVar(tipo, "ax");
                                        parser.pilaSemantica.push(RS_DO);
                                        parser.assemblyFile += "\tcall " + i.toString() + "\n";
                                    }   
                             
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expresion ::= EXCLAMACION exp 
            {
              Object RESULT =null;
		
                                RegistroSemanticoVar RS_DO = (RegistroSemanticoVar) parser.pilaSemantica.pop();
                                String var = parser.tablaSimbolos.getVarName();
                                IOperacion op = (IOperacion)new OperacionFactory("Not").getOp();
                                op.setOperandor(RS_DO);
                                op.setVarReturn(var);
                                String code = op.generarCodigo();
                                parser.assemblyFile += code;
                                RegistroSemanticoVar RS_RESULT = new RegistroSemanticoVar(RS_DO.getTipo(),var);
                                parser.pilaSemantica.push(RS_RESULT);

                             
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expresion ::= exp 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // sentencia ::= return_stmt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // sentencia ::= asignacion SEMICOLON 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // sentencia ::= expresion SEMICOLON 
            {
              Object RESULT =null;
		
                                System.out.println("===========================");
                                parser.pilaSemantica.pop(); 

                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // sentencia ::= while_statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // sentencia ::= variable 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // sentencia ::= if_statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // lista_sentencias ::= sentencia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // lista_sentencias ::= lista_sentencias sentencia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // bloque ::= error NT$3 decision_funcion 
            {
              Object RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // NT$3 ::= 
            {
              Object RESULT =null;
 parser.report_error(" no se encuentra el LBRACE o expresión inválida.","");  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$3",47, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // bloque ::= LBRACE RBRACE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // bloque ::= LBRACE lista_sentencias RBRACE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // bloque_global ::= error 
            {
              Object RESULT =null;
		 parser.report_error(" no se encuentra el LBRACE ACA .","");  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_global",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // bloque_global ::= LBRACE RBRACE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_global",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // bloque_global ::= LBRACE lista_sentencias RBRACE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_global",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // funcion ::= LPAREN error NT$2 RPAREN bloque_global 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // NT$2 ::= 
            {
              Object RESULT =null;
 parser.report_error(" parámetro incorrecto.",""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$2",46, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // funcion ::= LPAREN RPAREN bloque_global 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // def_funcion ::= LPAREN RPAREN SEMICOLON 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("def_funcion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // decision_operacion ::= funcion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decision_operacion",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // decision_operacion ::= def_funcion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decision_operacion",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // verification_part ::= validar_expr 
            {
              Object RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object exp = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("verification_part",35, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // id_fun_declaration ::= IDENTIFICADOR 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
                                        RegistroSemanticoSTMT RS_ID = new RegistroSemanticoSTMT(id.toString(), "RS_ID_F");//Crear RS_ID_F
                                        RS_ID.setStmt_label(parser.tablaSimbolos.getLabelName());
                                        parser.pilaSemantica.push(RS_ID);
                                        parser.assemblyFile += ((RegistroSemanticoSTMT)parser.pilaSemantica.searchRS("RS_ID_F")).getStmt_label()+": \n";
                                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("id_fun_declaration",43, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // id_declaration ::= IDENTIFICADOR 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
                                        parser.pilaSemantica.push(new RegistroSemantico(id.toString(), "RS_ID"));//Crear RS_ID
                                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("id_declaration",34, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // function_declaration_part ::= VOID 
            {
              Object RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object tipo = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
                                        parser.pilaSemantica.push(new RegistroSemantico(tipo.toString(), "RS_TIPO"));//Crear RS_Tipo
                                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_declaration_part",33, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // declaration_part ::= INT 
            {
              Object RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object tipo = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                                        parser.pilaSemantica.push(new RegistroSemantico(tipo.toString(), "RS_TIPO"));//Crear RS_Tipo
                                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaration_part",32, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // variable ::= declaration_part id_declaration verification_part SEMICOLON 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		  
                                    System.out.println("*************************************");
                                    RegistroSemantico RS_DO = parser.pilaSemantica.pop();
                                    String id,valor;
                                    if(RS_DO.getTipo()!="RS_ID"){
                                        RegistroSemantico RS_ID = parser.pilaSemantica.pop();
                                        System.out.println("::::::::::"+RS_ID.getToken());
                                        id=RS_ID.getToken();
                                        valor= RS_DO.getValor();
                                    }else{
                                        id=RS_DO.getToken();
                                        valor="0";
                                    }
                                    RegistroSemantico RS_TIPO = parser.pilaSemantica.pop();
                                    
                                    System.out.println("*************************************");
                                    if(parser.tablaSimbolos.get(id) == null){
                                        parser.tablaSimbolos.put(id, 
                                                                 new InfoKey("Identificador", 
                                                                              RS_TIPO.getToken(), 
                                                                              valor));
                                        parser.tablaSimbolos.get(id).setDireccion(valor);
                                        System.out.println("DATOS TABLA SIMBOLOS");
                                        System.out.println(id);
                                        System.out.println(((InfoKey) parser.tablaSimbolos.get(id)).getValor());
                                        System.out.println(((InfoKey) parser.tablaSimbolos.get(id)).getTipo());
                                        System.out.println(((InfoKey) parser.tablaSimbolos.get(id)).getCategoria());    
                                    }else{
                                        if(parser.tablaSimbolos.get(id).getNumDeclarado() <= 1){
                                            parser.tablaSimbolos.get(id).sumarDeclarado();
                                            parser.report_error(" identificador '" + id + "' ya ha sido declarado 1.", sleft,sright); 
                                        }
                                    }
                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variable",40, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // programa_c ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa_c",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // programa_c ::= declaration_part id_fun_declaration decision_operacion NT$1 programa_c 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa_c",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // NT$1 ::= 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;

                                    System.out.println("*************************************");
                                    
                                    RegistroSemantico RS_ID = parser.pilaSemantica.pop();
                                    RegistroSemantico RS_TIPO = parser.pilaSemantica.pop();

                                    System.out.println("DATOS DE LA FUNCIÓN-------------------");
                                    System.out.println(RS_ID.getToken());
                                    if(parser.tablaSimbolos.get(RS_ID.getToken()) == null ){                                    
                                        parser.tablaSimbolos.put(RS_ID.getToken(), 
                                                                 new InfoKey("Función", 
                                                                              RS_TIPO.getToken(),RS_ID.getToken())); 
                                        
                                        System.out.println("DATOS TABLA SIMBOLOS FUNCION INT");
                                        System.out.println(((InfoKey) parser.tablaSimbolos.get(RS_ID.getToken())).getValor());
                                        System.out.println(((InfoKey) parser.tablaSimbolos.get(RS_ID.getToken())).getTipo());
                                        System.out.println(((InfoKey) parser.tablaSimbolos.get(RS_ID.getToken())).getCategoria());
                                    }else{
                                        if(parser.tablaSimbolos.get(RS_ID.getToken()).getNumDeclarado() <= 1){
                                            parser.tablaSimbolos.get(RS_ID.getToken()).sumarDeclarado();
                                            parser.report_error(" identificador '" + RS_ID.getToken() + "' ya ha sido declarado.", sleft,sright); 
                                        }
                                    }
                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$1",45, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // programa_c ::= function_declaration_part id_fun_declaration decision_operacion NT$0 programa_c 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa_c",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // NT$0 ::= 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;

                                    RegistroSemantico RS_ID = parser.pilaSemantica.pop();
                                    RegistroSemantico RS_TIPO = parser.pilaSemantica.pop();
                                    System.out.println("DATOS DE LA FUNCIÓN-------------------");
                                    System.out.println(RS_ID.getToken());
                                    if(parser.tablaSimbolos.get(RS_ID.getToken()) == null){                                    
                                        parser.tablaSimbolos.put(RS_ID.getToken(), 
                                                                 new InfoKey("Función", 
                                                                              RS_TIPO.getToken())); 
                                        parser.assemblyFile += "\tret\n";
                                        System.out.println("DATOS TABLA SIMBOLOS FUNCION");
                                        System.out.println(((InfoKey) parser.tablaSimbolos.get(RS_ID.getToken())).getValor());
                                        System.out.println(((InfoKey) parser.tablaSimbolos.get(RS_ID.getToken())).getTipo());
                                        System.out.println(((InfoKey) parser.tablaSimbolos.get(RS_ID.getToken())).getCategoria());
                                    }else{
                                        if(parser.tablaSimbolos.get(RS_ID.getToken()).getNumDeclarado() <= 1){
                                            parser.tablaSimbolos.get(RS_ID.getToken()).sumarDeclarado();
                                            parser.report_error(" identificador '" + RS_ID.getToken() + "' ya ha sido declarado.", sleft,sright); 
                                        }
                                    }
                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$0",44, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa_c ::= variable programa_c 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa_c",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= programa_c 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

