
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 15 22:50:25 CST 2015
//----------------------------------------------------

package parser.data;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int RBRACK = 11;
  public static final int SEMICOLON = 12;
  public static final int ELSE = 16;
  public static final int RBRACE = 9;
  public static final int RPAREN = 7;
  public static final int EQUAL = 21;
  public static final int WHILE = 17;
  public static final int SUBSTRACT = 3;
  public static final int DIVISION = 5;
  public static final int LBRACK = 10;
  public static final int RETURN_TYPE = 25;
  public static final int MAYORQUE = 23;
  public static final int SWITCH = 20;
  public static final int IF = 15;
  public static final int LPAREN = 6;
  public static final int LBRACE = 8;
  public static final int DO = 18;
  public static final int COMMA = 13;
  public static final int EOF = 0;
  public static final int EXCLAMACION = 24;
  public static final int MENORQUE = 22;
  public static final int ADD = 2;
  public static final int LITERAL_ENTERO = 27;
  public static final int error = 1;
  public static final int DOT = 14;
  public static final int IDENTIFICADOR = 26;
  public static final int FOR = 19;
}

