
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 20 10:04:41 CST 2015
//----------------------------------------------------

package parser.data;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOREQ = 27;
  public static final int PLUSPLUS = 7;
  public static final int DIVEQ = 13;
  public static final int LITERAL_ENTERO = 39;
  public static final int MODEQ = 14;
  public static final int TIMESEQ = 12;
  public static final int LPAREN = 15;
  public static final int INT = 38;
  public static final int WRITE = 37;
  public static final int RPAREN = 16;
  public static final int IDENTIFICADOR = 41;
  public static final int SEMICOLON = 19;
  public static final int AND = 33;
  public static final int MAYORQUE = 28;
  public static final int OR = 32;
  public static final int COMMA = 21;
  public static final int PLUSEQ = 10;
  public static final int SUBSTRACT = 3;
  public static final int MINUSEQ = 11;
  public static final int ASSIGN = 9;
  public static final int IF = 22;
  public static final int LITERAL_CARACTER = 40;
  public static final int EXCLAMACION = 30;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 8;
  public static final int RETURN = 34;
  public static final int EQUAL = 25;
  public static final int error = 1;
  public static final int ADD = 2;
  public static final int VOID = 35;
  public static final int ERROR = 42;
  public static final int MENORQUE = 26;
  public static final int TIMES = 4;
  public static final int COLON = 20;
  public static final int LBRACE = 17;
  public static final int ELSE = 23;
  public static final int READ = 36;
  public static final int WHILE = 24;
  public static final int RBRACE = 18;
  public static final int MODULUS = 6;
  public static final int DIVISION = 5;
  public static final int MAYOREQ = 29;
  public static final int NOTEQ = 31;
}

