
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 17 20:56:05 CST 2015
//----------------------------------------------------

package parser.data;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOREQ = 32;
  public static final int PLUSPLUS = 7;
  public static final int DIVEQ = 12;
  public static final int LITERAL_ENTERO = 42;
  public static final int TIMESEQ = 11;
  public static final int CASE = 37;
  public static final int LPAREN = 13;
  public static final int FOR = 27;
  public static final int RPAREN = 14;
  public static final int IDENTIFICADOR = 41;
  public static final int SEMICOLON = 19;
  public static final int MAYORQUE = 33;
  public static final int COMMA = 21;
  public static final int RETURN_TYPE = 40;
  public static final int PLUSEQ = 9;
  public static final int SUBSTRACT = 3;
  public static final int MINUSEQ = 10;
  public static final int ASSIGN = 29;
  public static final int IF = 23;
  public static final int EXCLAMACION = 35;
  public static final int DOT = 22;
  public static final int EOF = 0;
  public static final int RETURN = 39;
  public static final int MINUSMINUS = 8;
  public static final int EQUAL = 30;
  public static final int error = 1;
  public static final int ADD = 2;
  public static final int SWITCH = 28;
  public static final int LBRACK = 17;
  public static final int MENORQUE = 31;
  public static final int COL = 20;
  public static final int TIMES = 4;
  public static final int LBRACE = 15;
  public static final int ELSE = 24;
  public static final int RBRACK = 18;
  public static final int WHILE = 25;
  public static final int DEFAULT = 38;
  public static final int RBRACE = 16;
  public static final int MODULUS = 6;
  public static final int DIVISION = 5;
  public static final int MAYOREQ = 34;
  public static final int DO = 26;
  public static final int NOTEQ = 36;
}

